name: create PR and Tag Docker Image

on:
    push:
      branches:
        - main  # Change this to your main branch
  
env:
    DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    IMAGE_TAG: ${{ github.sha }}
  
jobs:
    create-pr-and-tag-image:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
          with:
            token: ${{ secrets.PAT }}

        - name: release-please
          id: release
          uses: google-github-actions/release-please-action@v4.0.1
          
          with:
            release-type: node
            token: ${{ secrets.PAT }}
            target-branch: main
          # env:
          #  DEBUG: 'true'
  
        - name: Checkout code at release tag
          uses: actions/checkout@v2
          if: steps.release.outputs.env.IMAGE_TAG == 'true'
          with:
            ref: ${{ steps.release.outputs.env.IMAGE_TAG }}
            
    
        - name: Docker login
          uses: docker/login-action@v1
          with:
             username: ${{ secrets.DOCKERHUB_USERNAME }}
             password: ${{ secrets.DOCKERHUB_TOKEN }}
    
        - name: Docker build and tag
          run: |
            docker build -t karthickmuppilirajan/dockertag:${{ env.IMAGE_TAG }}  .
            docker push karthickmuppilirajan/dockertag:${{ env.IMAGE_TAG }} 
